version: "3"
services:
  client:
    restart: always
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    depends_on:
      - app
  app:
    build: ./app
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - my_net

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./mysqldata:/var/lib/mysql
    networks:
      - my_net

networks:
      my_net: